
title: "Data Chef"
description: "Recipes for data-wrangling and visualization (sample step-by-step projects)"
remote_theme: "mmistakes/minimal-mistakes@4.28.0"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "dark" # Options: air, aqua, contrast, dark, dir, neon, mint, sunrise

url: "https://rotsteinaviva-lab.github.io"
baseurl: "/data-chef"

sass:
  sass_dir: _sass

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

